name: AgorianRifts
version: 1.0.0
main: me.Lozke.AgorianRifts
author: Lozke
description: Let us pray it works.
api-version: 1.16
loadbefore: [Loot, PlayerMechanics, MobMechanics]
depend: [ProtocolLib]